### ISSUE TITLE
How to run the code with .sens file?

### ISSUE THREAD

**Issue by zhanlv600** [niessner/BundleFusion#11]
Hello, I compiled your code and it seemed that it couldn't run without the depth camera hard device. I found you provided the .sens file, so I wondered if the code could run with the .sens file? If it does, then how to run it with the .sens file?

**Comment by zhanlv600** [comment]
I get the answer. Edit the file zParametersDefault.txt: s_sensorIdx = **8**, and copy the .sens file in the project, use 3 arguments, example: zParametersDefault.txt zParametersBundlingDefault.txt test.sens, finally the program will run.

**Comment by kuonangzhe** [comment]
@zhanlv600 
hi, did you got the colored reconstruction result? I made it run but the window 'Fried Liver' showing is dark and the output results are also blank images(dark). Thank you so much!
