### ISSUE TITLE
How to get output data?

### ISSUE THREAD

**Issue by tansangxtt** [niessner/BundleFusion#3]
I cannot find the scene after scanning, please give me some instruction. Is it in 2 parameter files?

**Comment by tansangxtt** [comment]
I found it in DepthSensing.cpp. Your instruction should mention these functional keys

**Comment by kuonangzhe** [comment]
@tansangxtt 
Hi, I am trying to make this code work, too. Did you got the colored reconstruction result? I made it run but the window 'Fried Liver' showing is dark and the output results are also blank images(dark). Do you have any suggestions? Thank you so much!

**Comment by adammpolak** [comment]
@kuonangzhe what is your CUDA/VS/DirectX version?

**Comment by BruceWANGDi** [comment]
@kuonangzhe  Hi, I have the same issue with you, did you solve this problem? My environment is CUDA8.0, VS2013, Win10, but my GPU is RTX2080ti, I don't know whether my GPU can work on CUDA8.0.
