### ISSUE TITLE
The output file of apt0.sens seems have many regular cavities 

### ISSUE THREAD

**Issue by h1063135843** [niessner/BundleFusion#34]
I ran the program  with the default parameter. The input file is apt0.sens.  I viewed the output file in MeshLab, and it has many regular cavities. What's wrong with it?
![image](https://user-images.githubusercontent.com/26903569/49370772-31280f80-f730-11e8-811f-fa225637fd3a.png)

**Comment by FengLQy** [comment]
can you tell me how to run it by dataset?I don't have a depth camera, but I want to run it. thank you very much

**Comment by xiaomaoo** [comment]
How do you get the output file? is it a .ply file? 
the soure project seems not include the method to export the  ply model
Could you tell me please?

**Comment by h1063135843** [comment]
> How do you get the output file? is it a .ply file?
> the soure project seems not include the method to export the ply model
> Could you tell me please?

In fact, I ran the program and when it ended the output file appears automatically. It is a .ply file.

**Comment by xiaomaoo** [comment]
> > How do you get the output file? is it a .ply file?
> > the soure project seems not include the method to export the ply model
> > Could you tell me please?
> 
> In fact, I ran the program and when it ended the output file appears automatically. It is a .ply file.


Thanks for reply!
Have you modified any values in the two parameters.txt?
Is it scans/scan.ply?

**Comment by h1063135843** [comment]
> > > How do you get the output file? is it a .ply file?
> > > the soure project seems not include the method to export the ply model
> > > Could you tell me please?
> > 
> > 
> > In fact, I ran the program and when it ended the output file appears automatically. It is a .ply file.
> 
> Thanks for reply!
> Have you modified any values in the two parameters.txt?
> Is it scans/scan.ply?

It's not scan.ply. The name is the same as the input.  I just set the sensorIDX to 8 and change the path of Input file.

**Comment by h1063135843** [comment]
Sometimes I ran the kinect and press '9'  to save, the problem also occurs.  Sometimes it works perfectly and I don't know why.

**Comment by ElephantGit** [comment]
> I ran the program with the default parameter. The input file is apt0.sens. I viewed the output file in MeshLab, and it has many regular cavities. What's wrong with it?
> ![image](https://user-images.githubusercontent.com/26903569/49370772-31280f80-f730-11e8-811f-fa225637fd3a.png)
Hi, I have run the code on scene0000_00.sens, the output have many cavities, too. Do you solve this problem? If yes, how?
Thanks~

**Comment by Hegs30** [comment]
> > > How do you get the output file? is it a .ply file?
> > > the soure project seems not include the method to export the ply model
> > > Could you tell me please?
> > 
> > 
> > In fact, I ran the program and when it ended the output file appears automatically. It is a .ply file.
> 
> Thanks for reply!
> Have you modified any values in the two parameters.txt?
> Is it scans/scan.ply?

I can‘t get the output file too，did you finally get it？

**Comment by zhongtao93** [comment]
I get the same wrong output ply. Did anyone solve it?

![apt0_output](https://user-images.githubusercontent.com/15263824/87643337-52126c80-c77d-11ea-9647-664d004e7d21.png)

Thanks~

**Comment by h1063135843** [comment]
> I get the same wrong output ply. Did anyone solve it?
> 
> Thanks~

There is a parameter named s_marchingCubesMaxNumTriangles  in zParametersDefault.txt.
In marchingcube phase ,when the triangle number exceeds the threshold, the program will decrease triangle number first.
This is the reason leading to cavities.Try increase the parameter.
However, the max you could try depends on you GPU memory size.
