### ISSUE TITLE
The ply i generated was mess!

### ISSUE THREAD

**Issue by lixz123007** [niessner/BundleFusion#54]
16G i7-4720 gtx970 , win10 ,vs2013 ,cuda8.0 ,run atp0.sense : 
![image](https://user-images.githubusercontent.com/52441518/78233032-bc253f80-7507-11ea-9dce-b05bb45116da.png)
![image](https://user-images.githubusercontent.com/52441518/78233141-e545d000-7507-11ea-9a34-d9f53626f655.png)

![image](https://img-blog.csdnimg.cn/20200402172658686.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQwNzQzNjQy,size_16,color_FFFFFF,t_70)
https://img-blog.csdnimg.cn/20200402172658686.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzQwNzQzNjQy,size_16,color_FFFFFF,t_70

**Comment by wxq-888** [comment]
https://github.com/niessner/BundleFusion/issues/34#issue-386770700
