### ISSUE TITLE
Cuda 8.0

### ISSUE THREAD

**Issue by HyperLethalVector** [niessner/BundleFusion#9]
Is there a possibility to run this with cuda 8.0? I wish to use my gtx 1080 graphics card

**Comment by tansangxtt** [comment]
Yes, I also ran it successfully on GTX 1080 with CUDA 8.0

**Comment by carstenschwede** [comment]
It works with 7.5 and 8.0.

**Comment by adammpolak** [comment]
I got it to compile with cuda 9.1 #18
